[package]
name = "onething"
version = "0.1.0"
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"

[dependencies]
chrono = "*"
cpython = "*"
emerald-core = "*"
lazy_static = "*"
md5 = "*"
rand = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
